# Generated by Django 5.2.14 on 2026-05-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='squad',
            field=models.ManyToManyField(blank=True, related_name='matches_played', to='stats.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_conceded',
            field=models.PositiveIntegerField(default=0, verbose_name='Goals Conceded (For GK)'),
        ),
        migrations.CreateModel(
            name='GoalScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_scored', to='stats.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.ManyToManyField(to='stats.position'),
        ),
    ]
